hub/hub_frontend/config/routes.rb
Rpcserver::Application.routes.draw do

  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  scope "/admin" do
    resources :users
  end

  resources :token_authentications, :only => [:create, :destroy]

  resources :jobs, :only => [:index, :show, :destroy]

  resources :requests, :only => [:index, :show, :destroy]

  resources :metals, :only => [:index, :show, :destroy]

  resources :workers, :only => [:index, :show, :edit, :update, :destroy]

  root :to => "home#index"
end

hub/hub_frontend/app/views/layouts/_menu.html.erb
<li><%= link_to_if(can?(:read, "/"), "Home", root_path) %></li>
<% if can?(:read, Job) %><li><%= link_to("Jobs", jobs_path) %></li><% end %>
<% if can?(:read, Worker) %><li><%= link_to("Workers", workers_path) %></li><% end %>
<% if can?(:read, Metal) %><li><%= link_to("Metals", metals_path) %></li><% end %>
<% if can?(:read, Request) %><li><%= link_to("Requests", requests_path) %></li><% end %>
<% if can?(:read, User) %><li><%= link_to("Users", users_path) %></li><% end %>

hub/hub_frontend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rpcserver</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="menu">
    <ul class="hmenu">
      <%= render 'layouts/menu' %>
      <%= render 'devise/menu/login_items' %>
    </ul>
  </div>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>