hub/hub_frontend/config/routes.rb
Rpcserver::Application.routes.draw do

  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  scope "/admin" do
    resources :users
  end

  resources :token_authentications, :only => [:create, :destroy]

  resources :jobs, :only => [:index, :show, :destroy]

  resources :requests, :only => [:index, :show, :destroy]

  resources :metals, :only => [:index, :show, :destroy]

  resources :workers, :only => [:index, :show, :edit, :update, :destroy]

  root :to => "home#index"
end

hub/hub_frontend/app/models/worker.rb
class Worker < ActiveRecord::Base
  attr_accessible :ip, :name, :snapshottag, :vmimage, :vmname,
    :last_seen_at, :uuid, :state,
    :system, :architecture, :distribution, :capabilities, :platform
  belongs_to :metal
  has_one :job
end

hub/hub_frontend/app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @workers }
    end
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
    @worker = Worker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @worker }
    end
  end

  # GET /workers/1/edit
  def edit
    @worker = Worker.find(params[:id])
  end

  # PUT /workers/1
  # PUT /workers/1.json
  def update
    @worker = Worker.find(params[:id])

    respond_to do |format|
      if @worker.update_attributes(params[:worker])
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker = Worker.find(params[:id])
    @worker.destroy

    respond_to do |format|
      format.html { redirect_to workers_url }
      format.json { head :no_content }
    end
  end
end

hub/hub_frontend/app/helpers/workers_helper.rb
module WorkersHelper
  def WorkersHelper.update_from_metal_alive(metal, data)
      Rails.logger.info("Update worker from metal_alive #{data}")
      return if data['host-uuid'].nil?
      name = data['nodename']
      uuid = data['host-uuid']
      state = data['state']
      capabilities = data['capabilities']
      distribution = data['distribution']
      architecture = data['architecture']
      platform = data['platform']
      system = data['system']
      worker_data = {
        :name => name,
        :state => state,
        :capabilities => "#{capabilities}",
        :distribution => "#{distribution}",
        :architecture => architecture,
        :platform => platform,
        :system => system,
#        :last_seen_at => Time.now
      }

      Rails.logger.info("Looking for worker #{uuid}")
      worker = metal.workers.find_by_uuid(uuid)
      Rails.logger.info("found worker #{worker}")
      unless worker
        worker_data[:uuid] = uuid
        metal.workers.create(worker_data)
      else
        worker.update_attributes(worker_data)
        worker.save
      end
  end

end

hub/hub_frontend/app/views/workers/_form.html.erb
<%= form_for(@worker) do |f| %>
  <% if @worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
      <% @worker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vmimage %><br />
    <%= f.text_field :vmimage %>
  </div>
  <div class="field">
    <%= f.label :vmname %><br />
    <%= f.text_field :vmname %>
  </div>
  <div class="field">
    <%= f.label :snapshottag %><br />
    <%= f.text_field :snapshottag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hub/hub_frontend/app/views/workers/edit.html.erb
<h1>Edit worker <%= @worker.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', @worker %> |
<%= link_to 'Back', workers_path %>

hub/hub_frontend/app/views/workers/index.html.erb
<h1>Listing workers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>State</th>
    <th>Capabilities</th>
    <th>Platform</th>
    <th>Metal</th>
    <th>Last seen</th>
    <th></th>
    <th></th>
  </tr>

<% @workers.each do |worker| %>
  <tr>
    <td><%= link_to worker.name, worker %></td>
    <td><%= worker.state %></td>
    <td><%= worker.capabilities %></td>
    <td><%= worker.platform %></td>
    <td><%= link_to worker.metal.name, worker.metal if worker.metal %></td>
    <td><%= worker.last_seen_at %></td>
    <td><%= link_to 'Edit', edit_worker_path(worker) %></td>
    <td><%= link_to 'Destroy', worker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

hub/hub_frontend/app/views/workers/show.html.erb
<p>
  <b>Name:</b>
  <%= @worker.name %>
</p>

<p>
  <b>UUID:</b>
  <%= @worker.uuid %>
</p>

<p>
  <b>Metal:</b>
  <%= link_to @worker.metal.name, @worker.metal if @worker.metal %>
</p>

<p>
  <b>Vmimage:</b>
  <%= @worker.vmimage %>
</p>

<p>
  <b>Vmname:</b>
  <%= @worker.vmname %>
</p>

<p>
  <b>Snapshottag:</b>
  <%= @worker.snapshottag %>
</p>

<p>
  <b>Current Job:</b>
  <%= link_to @worker.job.id, @worker.job if @worker.job %>
</p>


<%= link_to 'Edit', edit_worker_path(@worker) %> |
<%= link_to 'Back', workers_path %>